#!/usr/bin/node

const config = require("./test/config.json")
console.log("Executing minimising script");

const fs = require('fs-extra');
fs.readdir("./build/contracts/", (err, files) => {
    if (err) {
        return console.log('Unable to scan directory: ' + err);
    } 

  fs.mkdir("./build/contracts/contracts/", ()=> {});
  files.forEach((file) => {
    fs.readFile(`./build/contracts/${file}`, 'utf8', (err, data) => {
      if (err) {
        console.log(`Error reading file from disk: ${err}`);
      } else {
        const databases = JSON.parse(data);
        let minContract = {
          abi: databases.abi,
          networks: databases.networks
        }

        data = JSON.stringify(minContract);
        fs.writeFile(`./build/contracts/contracts/${file}`, data, 'utf8', (err) => {
          if (err) {
            console.log(`Error writing file: ${err}`);
          } else {
            console.log(`${file} is written successfully!`);
          }
        });
      }
    });
  });
});


console.log("Coping contracts ..")

fs.rmdir(config.frontendPath + "src/contracts", () => {})
fs.copy("./build/contracts/contracts", config.frontendPath + "src/contracts");
