#!/usr/bin/node

console.log("Executing minimising script");

const fs = require('fs');
fs.readdir("./build/contracts/", (err, files) => {
    if (err) {
        return console.log('Unable to scan directory: ' + err);
    } 

  files.forEach((file) => {

    fs.readFile(`./build/contracts/${file}`, 'utf8', (err, data) => {
      if (err) {
        console.log(`Error reading file from disk: ${err}`);
      } else {
        const databases = JSON.parse(data);
        let minContract = {
          abi: databases.abi,
          networks: databases.networks
        }

        data = JSON.stringify(minContract);
        fs.writeFile(`./build/contracts/${file}`, data, 'utf8', (err) => {
          if (err) {
            console.log(`Error writing file: ${err}`);
          } else {
            console.log(`${file} is written successfully!`);
          }
        });
      }
    });
  });
});
